name: On Website Deploy
'on':
  push:
    branches:
      - "main"
jobs:
  on-push-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Enable Web
        run: flutter config --enable-web
      - name: Build Web application
        run: flutter build web
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_API_TOKEN }}
          publish_dir: ./build/web
